=== janluak/aws_schema/testing/test_data/database/schema_nested.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Nested Schema",
  "description": "This is an example schema for validating data against",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "some_string": {
      "description": "some key containing any kind of strings",
      "type": "string"
    },
    "some_int": {
      "description": "some key containing any integers",
      "type": "integer"
    },
    "some_float": {
      "description": "some key containing any floats",
      "type": "number"
    },
    "some_dict": {
      "description": "containing a simple dictionary",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "key1": {
          "description": "dictionary with key's value type string",
          "type": "string"
        },
        "key2": {
          "description": "dictionary with key's value type number",
          "type": "number"
        }
      }
    },
    "some_nested_dict": {
      "description": "containing a nested_dict",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "KEY1": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "subKEY1": {
              "type": "string"
            },
            "subKEY2": {
              "type": "number"
            },
            "subKEY3": {
              "$ref": "schema_nested_definitions.json#/definitions/third_nested_dict_key"
            },
            "subKEY4": {
              "patternProperties": {
                "^[a-z]+$": {
                  "type": "array",
                  "items": {
                    "$ref": "schema_nested_definitions.json#/definitions/fourth_nested_dict_key_array"
                  }
                },
                "^[a-z0-9]+$": {
                  "type": "array",
                  "items": {
                    "$ref": "schema_nested_definitions.json#/definitions/fourth_nested_dict_key_array"
                  }
                }
              }
            }
          }
        }
      }
    },
    "some_array": {
      "description": "contains a list",
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "number"
          },
          {
            "$ref": "schema_nested_array_child.json#/definitions/third_array_item"
          }
        ]
      }
    },
    "nested_array": {
      "description": "contains a list",
      "type": "array",
      "items": {
        "$ref": "schema_nested_array_child.json#/properties"
      }
    }
  },
  "required": [
    "some_string",
    "some_int",
    "some_float",
    "some_dict",
    "some_nested_dict",
    "nested_array"
  ]
}

=== janluak/aws_schema/testing/test_data/database/item_nested.json
{
  "some_string": "test",
  "some_int": 42,
  "some_float": 42.24,
  "some_dict": {
    "key1": "test_string",
    "key2": 3
  },
  "some_nested_dict": {
    "KEY1": {
      "subKEY1": "test_string",
      "subKEY2": 5
    }
  },
  "nested_array": [
    {
      "KEY1": {
        "subKEY1": "test_string1",
        "subKEY2": 1
      }
    },
    {
      "KEY1": {
        "subKEY1": "test_string2",
        "subKEY2": 2
      }
    },
    {
      "KEY1": {
        "subKEY1": "test_string3",
        "subKEY2": 3
      }
    }
  ]
}
